# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/ip/align_mul/align_mul.xci
# IP: The module: 'align_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alhua/VivadoProject/Normslize/Normslize.gen/sources_1/ip/align_mul/align_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'align_mul'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/ip/align_mul/align_mul.xci
# IP: The module: 'align_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alhua/VivadoProject/Normslize/Normslize.gen/sources_1/ip/align_mul/align_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'align_mul'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
