# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/bd/LayerNorm/ip/LayerNorm_accumulator_0_0/LayerNorm_accumulator_0_0.xci
# IP: The module: 'LayerNorm_accumulator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alhua/VivadoProject/Normslize/Normslize.gen/sources_1/bd/LayerNorm/ip/LayerNorm_accumulator_0_0/LayerNorm_accumulator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LayerNorm_accumulator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/bd/LayerNorm/ip/LayerNorm_accumulator_0_0/LayerNorm_accumulator_0_0.xci
# IP: The module: 'LayerNorm_accumulator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alhua/VivadoProject/Normslize/Normslize.gen/sources_1/bd/LayerNorm/ip/LayerNorm_accumulator_0_0/LayerNorm_accumulator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LayerNorm_accumulator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
