#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 31 20:27:37 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Layer_top_1batch_tb_behav -key {Behavioral:sim_1:Functional:Layer_top_1batch_tb} -tclbatch Layer_top_1batch_tb.tcl -protoinst "protoinst_files/LayerNorm.protoinst" -log simulate.log"
xsim Layer_top_1batch_tb_behav -key {Behavioral:sim_1:Functional:Layer_top_1batch_tb} -tclbatch Layer_top_1batch_tb.tcl -protoinst "protoinst_files/LayerNorm.protoinst" -log simulate.log

