# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/bd/LayerNorm/ip/LayerNorm_cal_var_top_0_0/LayerNorm_cal_var_top_0_0.xci
# IP: The module: 'LayerNorm_cal_var_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/ip/align_mul/align_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==align_mul || ORIG_REF_NAME==align_mul} -quiet] -quiet

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/ip/bf_sub/bf_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_sub || ORIG_REF_NAME==bf_sub} -quiet] -quiet

# XDC: /home/alhua/VivadoProject/Normslize/Normslize.gen/sources_1/bd/LayerNorm/ip/LayerNorm_cal_var_top_0_0/LayerNorm_cal_var_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LayerNorm_cal_var_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/bd/LayerNorm/ip/LayerNorm_cal_var_top_0_0/LayerNorm_cal_var_top_0_0.xci
# IP: The module: 'LayerNorm_cal_var_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/ip/align_mul/align_mul.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==align_mul || ORIG_REF_NAME==align_mul} -quiet] -quiet

# IP: /home/alhua/VivadoProject/Normslize/Normslize.srcs/sources_1/ip/bf_sub/bf_sub.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_sub || ORIG_REF_NAME==bf_sub} -quiet] -quiet

# XDC: /home/alhua/VivadoProject/Normslize/Normslize.gen/sources_1/bd/LayerNorm/ip/LayerNorm_cal_var_top_0_0/LayerNorm_cal_var_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LayerNorm_cal_var_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
